In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import matplotlib.pyplot as plt
import scipy.signal
import matplotlib.ticker as plticker
import time
from mpl_toolkits.axes_grid1 import make_axes_locatable
from tqdm import tqdm
from collections import defaultdict
from typing import Optional
from scipy.integrate import solve_ivp
from scipy.fftpack import diff as psdiff
import torch
import pytorch_lightning as pl
from torch import nn

import os, sys
sys.path.append(os.path.join(os.getcwd(), '../sympde'))

from data.dataset import PDEDataset, PDEDataModule
from data.utils import d_to_LT
from misc.utils import load_obj

from model.setup import setup_model
from model.networks.fno import FNO1d
from model.networks.lpsda_cnn import CNN, ResNet, BasicBlock1d
from model.learner import Learner

from model.networks.fno import FNO1d
from misc.utils import load_obj

from viz.plot_pde_data import plot_1ds, plot_1d_dict

from run import parse_options, main

In [2]:
splits = ['train', 'val', 'test']
for split in splits:
    us, dxs, dts = load_obj(f'../data/test/{split}/Pde1')
    print(len(us))

10
2
2


In [7]:
compute_lie_group_transformation(lie_algebra_generator)

array([[ 0.99500417, -0.09983342,  0.        ],
       [ 0.09983342,  0.99500417,  0.        ],
       [35.03976593, 15.72546837,  2.71828183]])

In [ ]:
def get_hparams(version):
    _, _, dim, r, digit, _, = version.split('_')
    dim = int(dim.replace('dim', ''))
    r = float(r.replace('r', ''))
    digit = digit.replace('digit', '')
    digit = int(digit) if digit != 'all' else digit
    return dim, r, digit

In [6]:
version = 'datav1_netCNN_Pde24_aug0_seed1_version_0'
_, net, pde, _, _, _, _= version.split('_')
net = net.replace('net', '')
return net, pde

('netCNN', 'Pde24')

In [2]:
import numpy as np

In [3]:
# Considering the previously defined matrices for L_exp and x_org
L_exp = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
                  [9, 8, 7, 6, 5, 4, 3, 2, 1],
                  [1, 1, 1, 1, 1, 1, 1, 1, 1],
                  [2, 2, 2, 2, 2, 2, 2, 2, 2],
                  [3, 3, 3, 3, 3, 3, 3, 3, 3],
                  [4, 4, 4, 4, 4, 4, 4, 4, 4],
                  [5, 5, 5, 5, 5, 5, 5, 5, 5],
                  [6, 6, 6, 6, 6, 6, 6, 6, 6],
                  [7, 7, 7, 7, 7, 7, 7, 7, 7]])

x_org = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute result = np.dot(L_exp, x_org.reshape(-1, 1))
result = np.dot(L_exp, x_org.reshape(-1, 1))

# Extracting the value of result[0, 0]
value_result_00 = result[0, 0]
print(value_result_00)


285


In [5]:
# Extracting the first row of L_exp and reshaped x_org
row_0_L_exp = L_exp[0, :]
reshaped_x_org = x_org.reshape(-1, 1)

# Computing result[0, 0] by taking the dot product of the first row of L_exp and reshaped x_org
result_00_explicit = np.dot(row_0_L_exp, reshaped_x_org)
print(result_00_explicit)


[285]


In [9]:
row_0_L_exp, reshaped_x_org

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]))

In [12]:
(row_0_L_exp * reshaped_x_org.reshape(-1)).sum()

285

In [7]:
np.array([i**2 for i in range(10)]).sum()

285

In [6]:
row_0_L_exp, reshaped_x_org

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]))