In [1]:
%load_ext autoreload
%autoreload 2

import sys, os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch import nn
import torchvision
from tqdm import tqdm
import torch.nn.functional as F

sys.path.append(os.path.join(os.getcwd(), '../symlie'))
sys.path.append(os.path.join(os.getcwd(), '../'))

In [14]:
x = torch.randn((2,))
x

tensor([-1.6853, -0.2056])

In [22]:
x.sum()

tensor(-1.8909)

In [17]:
l = nn.Linear(2, 3, bias = False)

l.weight.data = torch.tensor([[1., 2.], [3., 4.], [5., 6.]])


w = l.weight.data
w

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [18]:
l(x)

tensor([-2.0966, -5.8785, -9.6604], grad_fn=<SqueezeBackward4>)

In [19]:
x @ w.T

tensor([-2.0966, -5.8785, -9.6604])

In [20]:
w

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [21]:
class BinaryLinear(nn.Module):
    def __init__(self, input_features, output_features):
        super(BinaryLinear, self).__init__()
        # Initialize the weights as a Parameter
        self.weights = nn.Parameter(torch.randn(output_features, input_features))

    def forward(self, x):
        # Binarize the weights to 0 or 1
        binary_weights = torch.where(self.weights > 0, torch.ones_like(self.weights), torch.zeros_like(self.weights))
        # Perform the matrix multiplication without bias
        return F.linear(x, binary_weights)
    
bl = BinaryLinear(2, 3)

bl(x)

tensor([-1.6853, -1.8909, -0.2056])

In [11]:
mlp = torchvision.ops.MLP(
    in_channels = 2,
    hidden_channels = [3],
    bias = False
)

mlp

MLP(
  (0): Linear(in_features=2, out_features=3, bias=False)
  (1): Dropout(p=0.0, inplace=False)
)