In [2]:
import torch
import torch.nn.functional as F

In [21]:
a = torch.rand(size=(2,5))
a = F.normalize(a, p=1, dim=1)
print(a.sum(dim=1))

a* 100

tensor([1., 1.])


tensor([[28.9387,  3.3585, 17.0851, 27.2401, 23.3776],
        [18.4938,  4.7200, 20.5599, 29.1611, 27.0652]])

In [23]:
a.mean(dim=0)*100

tensor([23.7162,  4.0392, 18.8225, 28.2006, 25.2214])